name: Build

on:
  pull_request:
    types: [open, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: C4Builder
        uses: tobli/c4builder-action@patch-1
